### ISSUE TITLE
New script to detect UUID v1 in a HTTP response

### ISSUE THREAD

**Issue by righettod** [righettod/burp-piper-custom-scripts#2]
Based on the following articles:

- https://versprite.com/blog/universally-unique-identifiers/
- https://web.archive.org/web/20160305114945/http:/crypto-world.com/uuid/search_uuid.txt
- https://blog.silentsignal.eu/2017/02/17/not-so-unique-snowflakes/

Create a **Message viewers** script that will identify every **UUID v1** in a HTTP response body and extract the info about every **UUID** found.

**Comment by v-p-b** [comment]
Fun fact: @dnet (the creator of Piper) made an extension for this:

https://github.com/silentsignal/burp-uuid

Accompanying blog post:

https://blog.silentsignal.eu/2017/02/17/not-so-unique-snowflakes/

**Comment by righettod** [comment]
Hi, 

Thank a lot for the info about the additional blog post 👍 

Indeed, I have also noticed this during the reading of the article (very interesting one by the way) and it was by seeing this extension that I had the idea to create a script in this repo 😃

**Comment by righettod** [comment]
Implemented 😃
